name="blog"
version="0.0.1"
author="janiokq"
email="janiokq@gmail.com"

[server]
port=80
https_port=443
use_https=1
domain_name="localhost"
web_path="./web"
private_key_file="/Users/weeget/dev/rust/my_blog/nginx-selfsigned.key"
certificate_file="/Users/weeget/dev/rust/my_blog/nginx-selfsigned.crt"
[mongo]
ip="127.0.0.1"
port=27017
db_name="blog"
username=""
password=""

[jwt]
site_key="0F4EJz+1/hqVvFjuB8EcooQs1K6QKBvLUxqTHf4tixB="
claim_exp=10000000000